name       : bzflag
version    : 2.4.22
release    : 14
source     :
    - https://github.com/BZFlag-Dev/bzflag/archive/v2.4.22.tar.gz : a83122b429eff941ea0ede20c52865c11d1125c1d44efba8488d8a3bd7757526
homepage   : https://www.bzflag.org
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : games.arcade
summary    : BZFlag is a free online multiplayer 3D tank battle game
description: |
    BZFlag is an Open Source OpenGL multiplayer multiplatform Battle Zone capture the Flag game.  At its heart, the game is a 3D first person tank simulation where opposing teams battle for dominance.
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
setup      : |
    ./autogen.sh
    %configure --disable-static --libdir=%libdir%/bzflag
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 $pkgfiles/bzflag.desktop $installdir/usr/share/applications/bzflag.desktop
    install -Dm00644 data/bzflag-48x48.png $installdir/usr/share/pixmaps/bzflag.png

    install -Dm00644 $pkgfiles/bzflag.sysusers $installdir/%libdir%/sysusers.d/bzflag.conf
    install -Dm00644 $pkgfiles/bzflag.service $installdir/%libdir%/systemd/system/bzflag.service
