name       : bzflag
version    : 2.4.20
release    : 11
source     :
    - https://github.com/BZFlag-Dev/bzflag/archive/v2.4.20.tar.gz : 1b5e597f766e14fe4673ab21867513f73005820a7cc93c574e9c2622ffb2c119
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : games.arcade
summary    : BZFlag is a free online multiplayer 3D tank battle game
description: |
    BZFlag is an Open Source OpenGL multiplayer multiplatform Battle Zone
    capture the Flag game.  At its heart, the game is a 3D first person
    tank simulation where opposing teams battle for dominance.
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(krb5)
    - pkgconfig(libssh2)
    - pkgconfig(libssl)
    - pkgconfig(libnghttp2)
    - pkgconfig(sdl2)
    - c-ares-devel
setup      : |
    ./autogen.sh
    %configure --disable-static --libdir=%libdir%/bzflag
build      : |
    %make
install    : |
    %make_install

    install -D -m00644 $pkgfiles/bzflag.desktop $installdir/usr/share/applications/bzflag.desktop
    install -D -m00644 data/bzflag-48x48.png $installdir/usr/share/pixmaps/bzflag.png

    install -D -m00644 $pkgfiles/bzflag.sysusers $installdir/%libdir%/sysusers.d/bzflag.conf
    install -D -m00644 $pkgfiles/bzflag.service $installdir/%libdir%/systemd/system/bzflag.service
